project:
  type: website
  output-dir: docs

website:
  title: "OatNotes"
  navbar:
    logo: ./resource/episode_logo_v03_color.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    # title: "Contents"
    style: "floating"
    # style: "docked"
    search: true
    contents:
      - section: "Deep Learning"
      - section: "LazyVim"
        contents:
          - ./pages/lazyvim/lazyvim_tips.qmd
      - section: "Observable.js"
        contents:
          - ./pages/observable/observable_js.qmd
      - section: "Plotly_Dash"
        contents:
          - ./pages/plotly_dash/multiline_annotation.qmd
          - ./pages/plotly_dash/plotly_data_structure.qmd
          - ./pages/plotly_dash/transparent_fig_bgcolor.qmd
          - ./pages/plotly_dash/shape_3d.qmd
          - ./pages/plotly_dash/zt_dash_app.qmd
      - section: "Polars"
        contents:
          - ./pages/polars/merge_csvs.qmd
          - ./pages/polars/edit_df_column.qmd
          - ./pages/polars/polars_cookbook.qmd
          - ./pages/polars/polars_intro.qmd
          - ./pages/polars/polars_FAQ.qmd
      - section: "Quarto"
        contents:
          - ./pages/quarto/quarto_tabset.qmd
          - ./pages/quarto/expand_codeblock_width.qmd
          - ./pages/quarto/side_by_side_codeblock.qmd
      - section: "React"
        contents:
          - ./pages/react/react_intro.qmd
      - section: "rhino3dm"
        contents: 
          - ./pages/rhino3dm/test_rhino3dm.qmd
          - ./pages/rhino3dm/rhino3dm_01.qmd
          - ./pages/rhino3dm/rhino3dm_02.qmd
      - section: "shiny"
        contents: 
          - ./pages/shiny/shinylive_extension.qmd
          - ./pages/shiny/add_logo.qmd
          - ./pages/shiny/shiny_modules.qmd
      - section: "three.js"
        contents: 
          - ./pages/threejs/add_3js_code_blk.qmd
          - ./pages/threejs/embed_codesandbox.qmd

  back-to-top-navigation: true      
  page-navigation: true
  reader-mode: true

format:
  html:
    code-annotations: hover
    code-block-bg: true
    code-block-border-left: true
    code-copy: true
    code-fold: false
    code-line-numbers: true
    code-overflow: wrap
    code-tools: true
    css: styles.css
    grid:
      # sidebar-width: 300px
      # body-width: 900px
      body-width: 1000px
      # margin-width: 300px
      # gutter-width: 1.5rem
    number-sections: true
    theme: 
      dark: cyborg
      light: cosmo
    toc: true

  ipynb: default

filters: 
  - line-highlight
  - shinylive

highlight-style: breeze
