project:
  type: website
  output-dir: docs

website:
  title: "OatNotes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - dashboard.qmd

  sidebar:
    # title: "Contents"
    style: "floating"
    # style: "docked"
    search: true
    contents:
      - section: "Quarto"
        contents:
          - ./pages/quarto/quarto_tabset.qmd
          - ./pages/quarto/expand_codeblock_width.qmd
          - ./pages/quarto/side_by_side_codeblock.qmd
      - section: "Deep Learning"
      - section: "Plotly"
        contents:
          - ./pages/plotly/plotly_data_structure.qmd
          - ./pages/plotly/transparent_fig_bgcolor.qmd
      - section: "Observable.js"
        contents:
          - ./pages/observable/observable_js.qmd
      - section: "rhino3dm"
        contents: 
          - ./pages/rhino3dm/test_rhino3dm.qmd
        
format:
  html:
    code-block-bg: true
    code-block-border-left: true
    code-copy: true
    code-fold: false
    code-line-numbers: true
    code-tools: true
    css: styles.css
    grid:
      # sidebar-width: 300px
      # body-width: 900px
      body-width: 1000px
      # margin-width: 300px
      # gutter-width: 1.5rem
    theme: 
      light: flatly
      dark: darkly
    toc: true

  ipynb: default

filters: 
  - line-highlight

highlight-style: breeze
